
units:

# programming languages

  python3:
    files:
      - .pip-freeze
    requires-package:
      - bpython
    load-scripts-post: load_pip.sh
    save-scripts-pre: save_pip.sh

  node-nvm:
    install-command: 'curl -o- \"https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh\" | bash ; nvm install node'

# system utils

  bpytop:
    requires-package:
      - bpytop

  cava:
    requires-package:
      - cava

  tty-clock:
    install-command: 'cd ~ && git clone https://github.com/xorg62/tty-clock.git && make -C tty-clock install PREFIX="~/.local" && rm -rf tty-clock'

# shells

  zsh:
    files:
      - .zshrc
    requires-package:
      - zsh

  bash:
    files:
      - .bash_profile
      - .bashrc

# vim/neovim
  vim:
    files:
      - .vimrc

  neovim:
    files:
      - .config/nvim/*
      - .local/share/nvim/site
      - .local/share/nvim/*.vim
    exclude-files:
      - .config/nvim/plugged

    requires-package:
      - neovim

  nvim-plug:
    files:
      .local/share/nvim/site/autoload/plug.vim

# kde apps

  konsole:
    files:
      - .local/share/konsole
      - .local/share/kxmlgui5/konsole

  dolphin:
    files:
      - .local/share/dolphin
      - .local/share/kxmlgui5/dolphin

  kmail:
    files:
      - .local/share/kmail
      - .local/share/kxmlgui5/kmail

  kde-kxmlgui5:
    files:
      - .local/share/kxmlgui5/


# general kde config

  kde-plasma-fonts:
    files:
      - .config/kcmfonts
      - .config/kdeglobals
      - .config/kfontinstuirc

  krunner:
    files:
      - .config/krunnerrc

  kwin:
    files:
      - .config/kwinrc
      - .config/kwinrules
      - .local/share/kwin

  kde-plasma-core:
    preserve-symlinks: true
    files:
      - .local/share/plasma
      - .local/share/color-schemes
      - .local/share/icons
      - .local/share/wallpapers

      - .config/autostart
      - .config/autostart-scripts
      - .config/breezerc
      - .config/gtk*
      - .config/ksplashrc
      - .config/kdeglobals
      - .config/Trolltech.conf
      - .config/kcminputrc
      - .config/plasmarc
      - .config/kglobalshortcutsrc
      - .config/khotkeysrc
      - .config/kded5rc
      - .config/kscmserverrc
      - .config/plasmanotifyrc
      - .config/plasma-localerc
      - .config/ktimezonedrc

# Polybar
  polybar:
    files:
      - .config/polybar
    requires-package:
      - polybar
      - dbus-python

  dragon:
    install-command: "cd ~ && git clone git@github.com:mwh/dragon.git && cd dragon && make install && cd .. && rm dragon -rf && mv ~/.local/bin/dragon ~/.local/bin/drag"

  wezterm:
    files:
      - ~/.config/wezterm/
    requires-package:
      - wezterm


groups:
  programming-languages:
    units:
      - python3
      - node-nvm
  system-utils:
    units:
      - bpytop
      - cava
      - tty-clock
  wezterm:
    units:
      - wezterm
      - dragon
  kde-plasma-apps:
    units:
      - konsole
      - kmail
      - dolphin
      - kde-kxmlgui5
  kde-plasma-full:
    units:
      - kde-plasma-core
      - krunner
      - kde-plasma-fonts
      - kwin
      - polybar
    groups:
      - kde-plasma-apps
      - wezterm
  oh-my-zsh:
    units:
      - zsh

  neovim:
    units:
      - vim
      - neovim

  neovim-plugins:
    units:
      - nvim-plug
    groups:
      - neovim

package-managers:
  pacman:
    install: "pacman -S"
    remove: "pacman -R"
  yay:
    install: "yay -S"
    remove: "yay -R"
  apt:
    install: "apt install"
    remove: "apt remove"

packages:
  neovim:
    pacman: neovim
    apt: neovim
  bpython:
    pacman: bpython
    apt: bpython
  bpytop:
    pacman: bpytop
    apt: bpytop
  cava:
    apt: cava
    yay: cava
  polybar:
    apt: polybar
    yay: polybar
  dbus-python:
    pacman: dbus-python
    apt: python-dbus
  wezterm:
    apt: wezterm
    pacman: wezterm


environments:
  desktop:
    default-package-manager: pacman
    groups:
      - kde-plasma-full
      - oh-my-zsh
      - neovim-plugins
      - programming-languages
      - system-utils
  wsl:
    default-package-manager: apt
    groups:
      - oh-my-zsh
      - neovim-plugins
      - programming-languages
      - system-utils
